// You are given two strings s and t.
// String t is generated by random shuffling string s and then add one more letter at a random position.
// Return the letter that was added to t.

const findTheDifference = function(s, t) {
    [...s].forEach(char => {
        if (t.includes(char)) {
            t = t.replace(char, '')
        }
    })
    return t
};

// 1. Destructure s within array with destructuring assignment syntax and use forEach() method to iterate through the array
// 2. If t includes current char, set t equal to t with char removed by replacing char with empty string via replace() method
// 3. Return t