// You are given a string s consisting only of letters 'a' and 'b'. In a single step you can remove one palindromic subsequence from s.
// Return the minimum number of steps to make the given string empty.
// A string is a subsequence of a given string if it is generated by deleting some characters of a given string without changing its order. Note that a subsequence does not necessarily need to be contiguous.
// A string is called palindrome if is one that reads the same backward as well as forward.

const removePalindromeSub = s => s === "" ? 0 : (s === [...s].reverse().join("")) ? 1 : 2;

// 1. If "s" is an empty string, return 0
// 2. Else If, "s" is equal to s in reverse (is palindrome), return 1
// 3. Else return 2
